import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, Image, KeepTogether, HRFlowable)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


def generate_pdf_report(patient_name, patient_age, patient_gender, prediction,
                        confidence, image_path, heatmap_path, save_path,
                        patient_id=None, prediction_id=None,
                        report_id=None, date_of_birth=None):
    """
    Generates a fully structured clinical PDF report.
    Now includes: Report ID (GST-YYYYMMDD-XXXX), Date of Birth, and a
    GSTNet-branded footer on every page.
    """
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    # ── Colour palette ────────────────────────────────────────────────────────
    PRIMARY    = colors.HexColor("#0f52ba")
    ACCENT_RED = colors.HexColor("#d9534f")
    ACCENT_GRN = colors.HexColor("#2e8b57")
    GRAY_DARK  = colors.HexColor("#333333")
    GRAY_MID   = colors.HexColor("#666666")
    GRAY_LIGHT = colors.HexColor("#f0f4f8")
    BORDER     = colors.HexColor("#cccccc")

    # ── Page footer callback ──────────────────────────────────────────────────
    def add_footer(canvas, doc):
        canvas.saveState()
        footer_text = f"Generated by GSTNet Gallstone Detection System"
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(GRAY_MID)
        canvas.drawCentredString(letter[0] / 2, 28, footer_text)
        canvas.setStrokeColor(BORDER)
        canvas.setLineWidth(0.5)
        canvas.line(40, 36, letter[0] - 40, 36)
        canvas.restoreState()

    doc = SimpleDocTemplate(
        save_path, pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=40, bottomMargin=56,
        onFirstPage=add_footer, onLaterPages=add_footer
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'ReportTitle', parent=styles['Heading1'],
        fontName='Helvetica-Bold', fontSize=22,
        textColor=PRIMARY, spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        'Subtitle', parent=styles['Normal'],
        fontName='Helvetica', fontSize=10,
        textColor=GRAY_MID, spaceAfter=0
    )
    section_heading = ParagraphStyle(
        'SectionHeading', parent=styles['Heading2'],
        fontName='Helvetica-Bold', fontSize=12,
        textColor=PRIMARY, spaceBefore=10, spaceAfter=8
    )
    body_style = ParagraphStyle(
        'Body', parent=styles['BodyText'],
        fontName='Helvetica', fontSize=10.5,
        textColor=GRAY_DARK, leading=15
    )
    meta_style = ParagraphStyle(
        'Meta', parent=body_style,
        fontName='Helvetica-Oblique', fontSize=9,
        textColor=GRAY_MID
    )
    report_id_style = ParagraphStyle(
        'ReportID', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=13,
        textColor=PRIMARY
    )

    story = []

    # ── HEADER ────────────────────────────────────────────────────────────────
    header_data = [[
        Paragraph("<b>GSTNet Gallstone Detection Report</b>", title_style),
        Paragraph(f"Date: {datetime.now().strftime('%d %b %Y, %H:%M')}", meta_style)
    ]]
    header_table = Table(header_data, colWidths=[4.8*inch, 2.4*inch])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'BOTTOM'),
        ('ALIGN',  (1, 0), (1, 0),   'RIGHT'),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2, color=PRIMARY, spaceAfter=12))

    # ── REPORT ID BANNER ──────────────────────────────────────────────────────
    rid_display = report_id or "N/A"
    rid_banner = Table(
        [[Paragraph(f"Report ID: <b>{rid_display}</b>", report_id_style)]],
        colWidths=[7.2*inch]
    )
    rid_banner.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), colors.HexColor("#e8f0fe")),
        ('BOX',           (0, 0), (-1, -1), 1, PRIMARY),
        ('TOPPADDING',    (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING',   (0, 0), (-1, -1), 16),
    ]))
    story.append(rid_banner)
    story.append(Spacer(1, 14))

    # ── PATIENT DEMOGRAPHICS ──────────────────────────────────────────────────
    story.append(Paragraph("PATIENT INFORMATION", section_heading))

    p_id_str = f"PAT-{patient_id:05d}" if patient_id else "N/A"
    pr_id_str = f"RUN-{prediction_id:05d}" if prediction_id else "N/A"
    dob_display = date_of_birth or "N/A"

    demo_data = [
        ["Patient Name",  patient_name,     "Patient ID",    p_id_str],
        ["Gender",        patient_gender,    "Date of Birth", dob_display],
        ["Age",           f"{patient_age} years",  "Run Reference", pr_id_str],
    ]
    demo_rows = []
    for row in demo_data:
        demo_rows.append([
            Paragraph(f"<b>{row[0]}:</b>", body_style),
            Paragraph(str(row[1]), body_style),
            Paragraph(f"<b>{row[2]}:</b>", body_style),
            Paragraph(str(row[3]), body_style),
        ])

    demo_table = Table(demo_rows, colWidths=[1.6*inch, 2.0*inch, 1.4*inch, 2.2*inch])
    demo_table.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), GRAY_LIGHT),
        ('BOX',           (0, 0), (-1, -1), 0.5, BORDER),
        ('INNERGRID',     (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
        ('TOPPADDING',    (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING',   (0, 0), (-1, -1), 10),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 10),
    ]))
    story.append(demo_table)
    story.append(Spacer(1, 16))

    # ── DIAGNOSTIC RESULT CARD ────────────────────────────────────────────────
    story.append(Paragraph("DIAGNOSTIC ANALYSIS RESULT", section_heading))

    res_color = ACCENT_RED if prediction == "Gallstone" else ACCENT_GRN
    res_bg    = colors.HexColor("#fdf7f7") if prediction == "Gallstone" else colors.HexColor("#f5fbf5")
    verdict   = ("GALLSTONE DETECTED — Hyperechogenic focus with posterior acoustic shadow."
                 if prediction == "Gallstone"
                 else "NORMAL STUDY — Gallbladder wall smooth; no echogenic foci identified.")

    result_title_style = ParagraphStyle(
        'ResTitle', parent=body_style,
        fontSize=13, textColor=res_color, fontName='Helvetica-Bold'
    )

    result_data = [
        [Paragraph(f"Classification: <b>{prediction.upper()}</b>", result_title_style),
         Paragraph(f"Confidence: <b>{confidence * 100:.1f}%</b>", body_style)],
        [Paragraph(verdict, body_style), ""]
    ]
    result_table = Table(result_data, colWidths=[4.2*inch, 3.0*inch])
    result_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), res_bg),
        ('BOX',        (0, 0), (-1, -1), 1.5, res_color),
        ('SPAN',       (0, 1), (1, 1)),
        ('TOPPADDING',    (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING',   (0, 0), (-1, -1), 12),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 12),
    ]))
    story.append(result_table)
    story.append(Spacer(1, 20))

    # ── IMAGING PANEL ─────────────────────────────────────────────────────────
    story.append(Paragraph("ULTRASOUND IMAGING PANEL", section_heading))

    col_w = 3.35*inch
    row_h = 2.5*inch
    img_cells = [
        Paragraph("<i>Ultrasound scan unavailable</i>", body_style),
        Paragraph("<i>Grad-CAM heatmap unavailable</i>", body_style),
    ]
    try:
        if image_path and os.path.exists(image_path):
            img_cells[0] = Image(image_path, width=col_w, height=row_h)
    except Exception as e:
        print(f"Error loading scan image: {e}")
    try:
        if heatmap_path and os.path.exists(heatmap_path):
            img_cells[1] = Image(heatmap_path, width=col_w, height=row_h)
    except Exception as e:
        print(f"Error loading heatmap: {e}")

    img_data = [
        [img_cells[0], img_cells[1]],
        [Paragraph("<font color='#555555'><b>Figure A:</b> Original Ultrasound Scan</font>", meta_style),
         Paragraph("<font color='#555555'><b>Figure B:</b> Grad-CAM Explainability Map</font>", meta_style)]
    ]
    img_table = Table(img_data, colWidths=[3.6*inch, 3.6*inch])
    img_table.setStyle(TableStyle([
        ('ALIGN',   (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN',  (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 5),
        ('TOPPADDING',    (0, 1), (-1, 1), 4),
    ]))
    story.append(img_table)
    story.append(Spacer(1, 20))

    # ── METHODOLOGY FOOTNOTE ──────────────────────────────────────────────────
    story.append(Paragraph("GSTNet™ CLASSIFICATION METHODOLOGY", section_heading))
    story.append(Paragraph(
        "GSTNet (Gallstone Texture Network) is a dual-branch deep learning framework that fuses CNN-derived "
        "spatial features with a 24-dimensional GLCM + LBP texture vector. A Dual Attention Module (channel + "
        "spatial) refines the feature representation before final binary classification. Figure B (Grad-CAM) "
        "highlights the spatial regions of highest diagnostic influence for clinical interpretability.",
        body_style
    ))
    story.append(Spacer(1, 24))

    # ── SIGN-OFF ──────────────────────────────────────────────────────────────
    sign_data = [
        ["", "___________________________"],
        ["", "Authorised Clinician Signature"]
    ]
    sign_table = Table(sign_data, colWidths=[4.2*inch, 3.0*inch])
    sign_table.setStyle(TableStyle([
        ('ALIGN',    (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (1, 1), (1, 1),   'Helvetica-Bold'),
        ('FONTSIZE', (1, 1), (1, 1),   9),
        ('TEXTCOLOR',(1, 1), (1, 1),   GRAY_MID),
    ]))
    story.append(KeepTogether([sign_table]))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    return True
